config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :states

  mount Sidekiq::Web => '/sidekiq' #caminho para sidekiq/web  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/client", to: "clients#index"
  # Defines the root path route ("/")
  root "states#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
  validates :name, presence: true # Make sure the owner's name is present. 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    
  end
  
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: %i[ show edit update destroy ]

  # GET /states or /states.json
  def index
    @states = State.all
  end

  # GET /states/1 or /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states or /states.json
  def create
    sleep 20
    respond_to do |format|
      @state = State.new(state_params)

      if @state.save          
        InsertRecordsJob.perform_now(@state.id)

        format.html { redirect_to state_url(@state), notice: "State was successfully created." }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1 or /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to state_url(@state), notice: "State was successfully updated." }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1 or /states/1.json
  def destroy
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url, notice: "State was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:name, :attachment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap.min.css.map">

    <script src="/js/popper.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>

    <script src="/js/popper.min.js.map"></script>
    <script src="/js/bootstrap.min.js.map"></script>

    <title>ReadFileV3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/states/_form.html.erb
<div class="card shadow bg-white rounded">
<%= form_with(model: state) do |form| %>
  <% if state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
        <% state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block", class:"form-label" %>
    <%= form.text_field :name, class:"form-control form-control-sm" %>
  </div>

  <div class="form-group">
    <%= form.file_field :attachment, class:"form-control form-control-sm" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-info" %>
  </div>

<% end %>
</div>

app/views/states/_state.html.erb
<div id="<%= dom_id state %>">
  <p>
    <strong>Name:</strong>
    <%= state.name %>
  </p>

  <p>
    <strong>Attachment:</strong>
    <%= state.attachment %>
  </p>

</div>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Show this state", @state, class:"btn btn-primary" %>
  <%= link_to "Back to states", states_path, class:"btn btn-warning" %>
</div>

app/views/states/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
<h1>States</h1>
<div class="card shadow bg-white rounded">
<table class="table table-striped">
  <thead>
    <tr>
      <th>State Name</th>
      <th>Download Link</th>
      <th>Show State</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state|%>
      <tr>   
        <td>
          <%= state.name %>
        </td>   
        <td>
          <%= link_to "Download", state.attachment_url, download: '',  class:"btn btn-primary"%>
        </td>  
        <td>
          <%= link_to "Show state", state, class:"btn btn-success"%>
        </td> 
        <td>
          <%= button_to "Delete",  state, method: :delete, data: {confirm: "Are you sure you want to delete #{state.name}?"}, class:"btn btn-danger"%>
        </td>   
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= link_to "New state", new_state_path, class:"btn btn-primary" %>
</div>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Back to states", states_path, class:"btn btn-primary" %>
</div>

app/views/states/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <div class="card">
  <%= render @state %>
  </div>
  <br>

  <%= link_to "Show", @state.attachment_url, class:"btn btn-primary"%>

  <%= link_to "Edit this state", edit_state_path(@state), class:"btn btn-success" %>
  
  <%= link_to "Back to states", states_path, class:"btn btn-warning" %>

  <%= button_to "Destroy this state", @state, method: :delete, class:"btn btn-danger" %>  
</div>